Revert "Remove deprecated pkg_resources, replace with importlib"
This doesn't work...

    Traceback (most recent call last):
      File "/usr/bin/qvm-sync-appmenus", line 33, in <module>
        sys.exit(load_entry_point('qubesdesktop==4.2.8', 'console_scripts', 'qvm-sync-appmenus')())
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/qubesappmenus/receive.py", line 411, in main
        process_appmenus_templates(appmenusext, vm, new_appmenus)
      File "/usr/lib/python3.11/site-packages/qubesappmenus/receive.py", line 308, in process_appmenus_templates
        template_data = importlib.resources.files(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/importlib/resources/_common.py", line 22, in files
        return from_package(get_package(package))
                            ^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.11/importlib/resources/_common.py", line 55, in get_package
        raise TypeError(f'{package!r} is not a package')
    TypeError: 'qubesappmenus.receive' is not a package

This reverts commit 173fd24a12049818e28d2b979c753e77163c6083.